[build-system]

requires = ["setuptools",
            "setuptools_scm",
            "wheel",
            "lxml"]

build-backend = 'setuptools.build_meta'


[tool.black]
force-exclude = '''
(
  .*
)
'''